# permissions for end users to view networkconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkconfiguration-viewer-role
rules:
- apiGroups:
  - network.fennecproject.io
  resources:
  - networkconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.fennecproject.io
  resources:
  - networkconfigurations/status
  verbs:
  - get
