# permissions for end users to view networkprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkprofile-viewer-role
rules:
- apiGroups:
  - network.fennecproject.io
  resources:
  - networkprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.fennecproject.io
  resources:
  - networkprofiles/status
  verbs:
  - get
