# permissions for end users to edit networkconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkconfiguration-editor-role
rules:
- apiGroups:
  - network.fennecproject.io
  resources:
  - networkconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.fennecproject.io
  resources:
  - networkconfigurations/status
  verbs:
  - get
