# permissions for end users to edit networkprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkprofile-editor-role
rules:
- apiGroups:
  - network.fennecproject.io
  resources:
  - networkprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.fennecproject.io
  resources:
  - networkprofiles/status
  verbs:
  - get
