## Append samples you want in your CSV to this file as resources ##
resources:
- network_v1alpha1_networkprofile.yaml
- network_v1alpha1_networkprofileclass.yaml
- network_v1alpha1_networkconfiguration.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
